[FIX] Permite imprimir o DANFE de um XML não autorizado
erpbrasil/erpbrasil.edoc.pdf pull request #16
Opened 2021-11-30 13:32 UTC by renatonlima

replaces #12

2021-11-30 14:27 UTC, marcelsavegnago approved these changes

2021-12-01 14:20 UTC, rvalyi approved these changes

2021-12-01 20:26 UTC, renatonlima commented
Pessoal,

Eu vou converter esse PR em draft porque existe um problema neste método: https://github.com/erpbrasil/erpbrasil.edoc.pdf/blob/92ae34f668baa1da52275633db2351443c405064/src/erpbrasil/edoc/pdf/nfe.py#L88

Aqui ele deveria chamar o método e passar o argumento sem ser uma string para a mudança desse PR funcionar como esperado.

2022-08-30 14:25 UTC, mileo approved these changes

2022-08-30 14:26 UTC, mileo requested changes
Alguma previsão de finalização?

2023-01-04 12:55 UTC, renatonlima commented
Replaced by PR #25

2023-01-04 12:55 UTC, closed without merging