Atualização do DANFE
erpbrasil/erpbrasil.edoc.pdf pull request #21
Opened 2022-08-19 16:04 UTC by renatonlima

Atualização do DANFE:

Rodapé do Danfe;
Adicionado valore dos impostos II, PIS, COFINS, DIFAL;
Corrigida a condição para não mostrar os campos de duplicatas caso não tenha nenhuma duplicata.

2022-08-19 17:29 UTC, marcelsavegnago approved these changes

2022-08-30 14:23 UTC, mileo commented
@renatonlima fiz o merge do #20 que veio primeiro, vc pode usar o odt como modelo para incluir suas adaptações?

2022-08-30 14:24 UTC, mileo requested changes
conforme comentado

2023-01-04 12:53 UTC, renatonlima commented
Replaced by #25

2023-01-04 12:53 UTC, closed without merging